```{r, fig.height=8}
library(readr)
library(lubridate)
library(janitor)
library(tidyr)
library(dplyr)
library(tidyverse)
library(kableExtra)
library(tinytex)
library(htmltools)


athletes <- read_csv("athlete_events.csv")
noc <- read_csv("noc_regions.csv")
gdp <- read_csv("gdp_1960_2020.csv")
population <- readRDS("population.rds")

gdp_all <- readRDS("gdp_all.rds")%>%
  mutate(Year = as.character(Year)) %>%
  mutate(region = case_when(Country == "United States" ~ "USA", 
                            Country == "United Kingdom" ~ "UK",
                            T ~ Country))%>%
  select(Year, region, gdp)

population2016 <- population %>%
  filter(Year == "2016")

names <- noc %>%
  rename(Country = region)%>%
  select(NOC, Country)

medal_gdp <- athletes %>%
  filter(!is.na(Medal))%>%
  group_by(NOC, Games)%>%
  summarise(
    Gold = sum(Medal == "Gold"),
    Silver = sum(Medal == "Silver"),
    Bronze = sum(Medal == "Bronze"))%>%
  inner_join(noc)%>%
  separate(Games, into = c("Year", "Season"), sep = " ")%>% 
  select(NOC, Year, Gold, Silver, Bronze, region) %>%
  inner_join(gdp_all, by = c("Year", "region"))%>%
  group_by(region, Year) %>%
  summarise(total_medals = sum(Gold, Silver, Bronze), gdp = gdp) %>%
  unique()

medal_gdp_2016 <- medal_gdp%>%
  filter(Year == "2016")%>%
  rename(Country = region)

gdp_pop_medal_2016 <-medal_gdp_2016%>%
  inner_join(population2016, by = "Country")%>%
  rename(Year= Year.x, Population = Count)%>%
  select(-Year.y)

saveRDS(gdp_pop_medal_2016, file = "2016_gdp_pop.rds")


setdiff(unique(gdp_all$Country), medal_gdp$region)

medals <- athletes %>%
  filter(!is.na(Medal))%>%
  group_by(NOC, Games)%>%
  summarise(
    Gold = sum(Medal == "Gold"),
    Silver = sum(Medal == "Silver"),
    Bronze = sum(Medal == "Bronze"))%>%
  inner_join(noc)%>%
  mutate(Month = case_when(grepl("Summer", Games) ~ 7, 
                           grepl("Winter", Games)~ 2))%>%
  separate(Games, into = c("Year", "Season"), sep = " ")%>% 
  mutate(time = make_date(year = Year, month = Month))%>% 
  select(region, time, Gold, Silver, Bronze)

saveRDS(medals, file = "ALL_medals.rds")

usamedals <- medals %>%
  filter(region == "USA")%>%
  pivot_longer(cols = c(Gold, Silver, Bronze), names_to = "Type", values_to = "Count")%>%
  separate(Games, into = c("Year", "Season"), sep = " ")%>%
  filter(Year >= 1992)%>%
  mutate(Type = factor(Type, level = c("Gold", "Silver", "Bronze") ) )%>%
  mutate(Month = case_when(grepl("Summer",Season) ~ 7, 
                           grepl("Winter", Season)~ 2))

  saveRDS(usamedals, file = "USA_Medals.rds")

ggplot(data = usamedals, aes(x= Year, y = Count))+
        facet_wrap(~Type)+
        geom_col(aes(fill = Season), position = "dodge")+ 
      labs(x="Year", y= "Count", title = " Medals")+
   theme(axis.text.x = element_text(angle = 90))+ ylim(c(0,160))
```




```{r}
russiamedals <- medals %>%
  filter(region == "Russia")%>%
  pivot_longer(cols = c(Gold, Silver, Bronze), names_to = "Type", values_to = "Count")%>%
  separate(Games, into = c("Year", "Season"), sep = " ")%>%
  filter(Year >= 1992)%>%
  mutate(Type = factor(Type, level = c("Gold", "Silver", "Bronze") ) )

ggplot(data = russiamedals, aes(x= Year, y = Count))+
        facet_wrap(~Type)+
        geom_col(aes(fill = Season), position = "dodge")+ 
      labs(x="Year", y= "Count", title = " Medals won by Russia")+
   theme(axis.text.x = element_text(angle = 90))+ ylim(c(0,100))

```


```{r}
germanymedals <- medals %>%
  filter(region == "Germany")%>%
  pivot_longer(cols = c(Gold, Silver, Bronze), names_to = "Type", values_to = "Count")%>%
  separate(Games, into = c("Year", "Season"), sep = " ")%>%
  filter(Year >= 1992)%>%
  mutate(Type = factor(Type, level = c("Gold", "Silver", "Bronze") ) )

ggplot(data = germanymedals, aes(x= Year, y = Count))+
        facet_wrap(~Type)+
        geom_col(aes(fill = Season), position = "dodge")+ 
      labs(x="Year", y= "Count", title = " Medals")+
   theme(axis.text.x = element_text(angle = 90))+ ylim(c(0,85))
```

